/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carsharing;

/**
 *
 * @author Amine Sahraoui
 */
public class Inserisci extends javax.swing.JFrame {

    /**
     * Creates new form Inserisci
     */
    public Inserisci() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitoloInserisci = new javax.swing.JLabel();
        lblInserisciTarga = new javax.swing.JLabel();
        btnInserisciAuto = new javax.swing.JButton();
        txtInserisciTarga = new javax.swing.JTextField();
        ComboBoxParcheggio = new javax.swing.JComboBox<>();
        lblInserisciParcheggio = new javax.swing.JLabel();
        btnIndietroAuto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lblTitoloInserisci.setFont(new java.awt.Font("Caladea", 3, 24)); // NOI18N
        lblTitoloInserisci.setForeground(new java.awt.Color(153, 51, 255));
        lblTitoloInserisci.setText("Aggiungi auto ");
        lblTitoloInserisci.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblInserisciTarga.setFont(new java.awt.Font("Caladea", 3, 18)); // NOI18N
        lblInserisciTarga.setForeground(new java.awt.Color(153, 51, 255));
        lblInserisciTarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInserisciTarga.setText("Inserisci targa");
        lblInserisciTarga.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnInserisciAuto.setFont(new java.awt.Font("Caladea", 2, 18)); // NOI18N
        btnInserisciAuto.setText("Inserisci");
        btnInserisciAuto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255)));

        ComboBoxParcheggio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblInserisciParcheggio.setFont(new java.awt.Font("Caladea", 3, 18)); // NOI18N
        lblInserisciParcheggio.setForeground(new java.awt.Color(153, 51, 255));
        lblInserisciParcheggio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInserisciParcheggio.setText("Seleziona Parcheggio");
        lblInserisciParcheggio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnIndietroAuto.setFont(new java.awt.Font("Caladea", 2, 18)); // NOI18N
        btnIndietroAuto.setText("X");
        btnIndietroAuto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255)));
        btnIndietroAuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIndietroAutoMouseClicked(evt);
            }
        });
        btnIndietroAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndietroAutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitoloInserisci)
                .addGap(80, 80, 80)
                .addComponent(btnIndietroAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInserisciTarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtInserisciTarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInserisciParcheggio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxParcheggio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnInserisciAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitoloInserisci)
                    .addComponent(btnIndietroAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInserisciTarga)
                    .addComponent(lblInserisciParcheggio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInserisciTarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxParcheggio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(btnInserisciAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIndietroAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndietroAutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIndietroAutoActionPerformed

    private void btnIndietroAutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIndietroAutoMouseClicked
        setVisible(false);
    }//GEN-LAST:event_btnIndietroAutoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inserisci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inserisci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inserisci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inserisci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inserisci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxParcheggio;
    private javax.swing.JButton btnIndietroAuto;
    private javax.swing.JButton btnInserisciAuto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInserisciParcheggio;
    private javax.swing.JLabel lblInserisciTarga;
    private javax.swing.JLabel lblTitoloInserisci;
    private javax.swing.JTextField txtInserisciTarga;
    // End of variables declaration//GEN-END:variables
}
