/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carsharing;

/**
 *
 * @author Amine Sahraoui
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    private NewParcheggio parcheggio;
    private Inserisci auto;
    private Rimuovi rimuovi;
    private Statistiche statistiche;
    private Transita transita;
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCarSharingTitolo = new javax.swing.JLabel();
        btnInserisciAutoHome = new javax.swing.JButton();
        btnTransitaHome = new javax.swing.JButton();
        btnRimuoviHome = new javax.swing.JButton();
        btnInserisciNewParcheggioHome = new javax.swing.JButton();
        btnStatisticheHome = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        lblHomeInfo1 = new javax.swing.JLabel();
        lblNumHomeInfo1 = new javax.swing.JLabel();
        lblHomeInfo2 = new javax.swing.JLabel();
        lblNumHomeInfo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCarSharingTitolo.setFont(new java.awt.Font("Caladea", 3, 30)); // NOI18N
        lblCarSharingTitolo.setText("Car Sharing");

        btnInserisciAutoHome.setFont(new java.awt.Font("Caladea", 2, 18)); // NOI18N
        btnInserisciAutoHome.setText("Inserisci Auto");
        btnInserisciAutoHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255)));
        btnInserisciAutoHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInserisciAutoHomeMouseClicked(evt);
            }
        });

        btnTransitaHome.setFont(new java.awt.Font("Caladea", 2, 18)); // NOI18N
        btnTransitaHome.setText("Transita");
        btnTransitaHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255)));
        btnTransitaHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransitaHomeMouseClicked(evt);
            }
        });

        btnRimuoviHome.setFont(new java.awt.Font("Caladea", 2, 18)); // NOI18N
        btnRimuoviHome.setText("Rimuovi");
        btnRimuoviHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255)));
        btnRimuoviHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRimuoviHomeMouseClicked(evt);
            }
        });

        btnInserisciNewParcheggioHome.setFont(new java.awt.Font("Caladea", 2, 18)); // NOI18N
        btnInserisciNewParcheggioHome.setText("Nuovo Parcheggio");
        btnInserisciNewParcheggioHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255)));
        btnInserisciNewParcheggioHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInserisciNewParcheggioHomeMouseClicked(evt);
            }
        });

        btnStatisticheHome.setFont(new java.awt.Font("Caladea", 2, 18)); // NOI18N
        btnStatisticheHome.setText("Statistiche");
        btnStatisticheHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255)));
        btnStatisticheHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStatisticheHomeMouseClicked(evt);
            }
        });

        lblHomeInfo1.setText("Parcheggi disponibili:");

        lblNumHomeInfo1.setText("Num");

        lblHomeInfo2.setText("Parcheggi occupati:");

        lblNumHomeInfo2.setText("Num");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addComponent(lblCarSharingTitolo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnInserisciNewParcheggioHome, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnStatisticheHome, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnInserisciAutoHome, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(120, 120, 120)
                                        .addComponent(btnTransitaHome, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                                        .addComponent(btnRimuoviHome, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHomeInfo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumHomeInfo1)
                        .addGap(18, 18, 18)
                        .addComponent(lblHomeInfo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumHomeInfo2)))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblCarSharingTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumHomeInfo2)
                    .addComponent(lblHomeInfo1)
                    .addComponent(lblNumHomeInfo1)
                    .addComponent(lblHomeInfo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInserisciNewParcheggioHome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(btnStatisticheHome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransitaHome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInserisciAutoHome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRimuoviHome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserisciNewParcheggioHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInserisciNewParcheggioHomeMouseClicked
        parcheggio=new NewParcheggio();
        parcheggio.setLocationRelativeTo(this.auto);
        parcheggio.setVisible(true);
        
    }//GEN-LAST:event_btnInserisciNewParcheggioHomeMouseClicked

    private void btnStatisticheHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatisticheHomeMouseClicked
        statistiche=new Statistiche();
        statistiche.setLocationRelativeTo(this.auto);
        statistiche.setVisible(true);
    }//GEN-LAST:event_btnStatisticheHomeMouseClicked

    private void btnInserisciAutoHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInserisciAutoHomeMouseClicked
        auto=new Inserisci();
        auto.setLocationRelativeTo(this.auto);
        auto.setVisible(true);
    }//GEN-LAST:event_btnInserisciAutoHomeMouseClicked

    private void btnTransitaHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransitaHomeMouseClicked
        transita=new Transita();
        transita.setLocationRelativeTo(this.auto);
        transita.setVisible(true);
    }//GEN-LAST:event_btnTransitaHomeMouseClicked

    private void btnRimuoviHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRimuoviHomeMouseClicked
        rimuovi=new Rimuovi();
        rimuovi.setLocationRelativeTo(this.auto);
        rimuovi.setVisible(true);
    }//GEN-LAST:event_btnRimuoviHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserisciAutoHome;
    private javax.swing.JButton btnInserisciNewParcheggioHome;
    private javax.swing.JButton btnRimuoviHome;
    private javax.swing.JButton btnStatisticheHome;
    private javax.swing.JButton btnTransitaHome;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCarSharingTitolo;
    private javax.swing.JLabel lblHomeInfo1;
    private javax.swing.JLabel lblHomeInfo2;
    private javax.swing.JLabel lblNumHomeInfo1;
    private javax.swing.JLabel lblNumHomeInfo2;
    // End of variables declaration//GEN-END:variables
}
