/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carsharing;

/**
 *
 * @author Amine Sahraoui
 */
public class NewParcheggio extends javax.swing.JFrame {

    /**
     * Creates new form NewParcheggio
     */
    public NewParcheggio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        lblNomeNewParcheggio = new javax.swing.JLabel();
        lblMaxPostiNewParcheggio = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        lblNewParcheggioTitolo = new javax.swing.JLabel();
        btnInserisciNewParcheggio = new javax.swing.JButton();
        btnIndietroNewParcheggio = new javax.swing.JButton();

        setLocation(new java.awt.Point(100, 100));
        setUndecorated(true);

        lblNomeNewParcheggio.setFont(new java.awt.Font("Caladea", 3, 18)); // NOI18N
        lblNomeNewParcheggio.setForeground(new java.awt.Color(153, 51, 255));
        lblNomeNewParcheggio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeNewParcheggio.setText("Inserisci nome");

        lblMaxPostiNewParcheggio.setFont(new java.awt.Font("Caladea", 3, 18)); // NOI18N
        lblMaxPostiNewParcheggio.setForeground(new java.awt.Color(153, 51, 255));
        lblMaxPostiNewParcheggio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaxPostiNewParcheggio.setText("Inserisci posti massimi");

        lblNewParcheggioTitolo.setFont(new java.awt.Font("Caladea", 3, 24)); // NOI18N
        lblNewParcheggioTitolo.setForeground(new java.awt.Color(153, 51, 255));
        lblNewParcheggioTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewParcheggioTitolo.setText("Aggiungi Parcheggio");

        btnInserisciNewParcheggio.setFont(new java.awt.Font("Caladea", 2, 18)); // NOI18N
        btnInserisciNewParcheggio.setText("Inserisci");
        btnInserisciNewParcheggio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255)));

        btnIndietroNewParcheggio.setFont(new java.awt.Font("Caladea", 2, 18)); // NOI18N
        btnIndietroNewParcheggio.setText("X");
        btnIndietroNewParcheggio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255)));
        btnIndietroNewParcheggio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIndietroNewParcheggioMouseClicked(evt);
            }
        });
        btnIndietroNewParcheggio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndietroNewParcheggioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addComponent(lblNewParcheggioTitolo)
                .addGap(48, 48, 48)
                .addComponent(btnIndietroNewParcheggio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaxPostiNewParcheggio)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeNewParcheggio)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btnInserisciNewParcheggio, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewParcheggioTitolo)
                    .addComponent(btnIndietroNewParcheggio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(lblNomeNewParcheggio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMaxPostiNewParcheggio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnInserisciNewParcheggio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIndietroNewParcheggioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndietroNewParcheggioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIndietroNewParcheggioActionPerformed

    private void btnIndietroNewParcheggioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIndietroNewParcheggioMouseClicked
        setVisible(false);
    }//GEN-LAST:event_btnIndietroNewParcheggioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewParcheggio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewParcheggio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewParcheggio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewParcheggio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewParcheggio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIndietroNewParcheggio;
    private javax.swing.JButton btnInserisciNewParcheggio;
    private javax.swing.JLabel lblMaxPostiNewParcheggio;
    private javax.swing.JLabel lblNewParcheggioTitolo;
    private javax.swing.JLabel lblNomeNewParcheggio;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome1;
    // End of variables declaration//GEN-END:variables
}
