/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carsharing;

/**
 *
 * @author Amine Sahraoui
 */
public class Statistiche extends javax.swing.JFrame {

    /**
     * Creates new form Statistiche
     */
    public Statistiche() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatisticheTitolo = new javax.swing.JLabel();
        lblParchMaxPosti = new javax.swing.JLabel();
        lblParchMinPosti = new javax.swing.JLabel();
        lblTotAutoParch = new javax.swing.JLabel();
        lblMaxAutoParch = new javax.swing.JLabel();
        lblMediaAutoParch = new javax.swing.JLabel();
        lblMediaNViaggi = new javax.swing.JLabel();
        lblNumStat1 = new javax.swing.JLabel();
        lblNumStat2 = new javax.swing.JLabel();
        lblNumStat3 = new javax.swing.JLabel();
        lblNumStat4 = new javax.swing.JLabel();
        lblNumStat5 = new javax.swing.JLabel();
        lblNumStat6 = new javax.swing.JLabel();
        btnIndietroStats = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lblStatisticheTitolo.setFont(new java.awt.Font("Caladea", 3, 24)); // NOI18N
        lblStatisticheTitolo.setForeground(new java.awt.Color(153, 51, 255));
        lblStatisticheTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatisticheTitolo.setText("Statistiche");

        lblParchMaxPosti.setFont(new java.awt.Font("Caladea", 2, 14)); // NOI18N
        lblParchMaxPosti.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblParchMaxPosti.setText("Parcheggio più posti:");

        lblParchMinPosti.setFont(new java.awt.Font("Caladea", 2, 14)); // NOI18N
        lblParchMinPosti.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblParchMinPosti.setText("Parcheggio meno posti:");

        lblTotAutoParch.setFont(new java.awt.Font("Caladea", 2, 14)); // NOI18N
        lblTotAutoParch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotAutoParch.setText("Auto tot nel parcheggio:");

        lblMaxAutoParch.setFont(new java.awt.Font("Caladea", 2, 14)); // NOI18N
        lblMaxAutoParch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMaxAutoParch.setText("Auto tot massime:");

        lblMediaAutoParch.setFont(new java.awt.Font("Caladea", 2, 14)); // NOI18N
        lblMediaAutoParch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMediaAutoParch.setText("Media auto/parcheggio:");

        lblMediaNViaggi.setFont(new java.awt.Font("Caladea", 2, 14)); // NOI18N
        lblMediaNViaggi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMediaNViaggi.setText("Media num viaggi:");

        lblNumStat1.setFont(new java.awt.Font("Caladea", 2, 14)); // NOI18N
        lblNumStat1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNumStat1.setText("NUM");

        lblNumStat2.setFont(new java.awt.Font("Caladea", 2, 14)); // NOI18N
        lblNumStat2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNumStat2.setText("NUM");

        lblNumStat3.setFont(new java.awt.Font("Caladea", 2, 14)); // NOI18N
        lblNumStat3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNumStat3.setText("NUM");

        lblNumStat4.setFont(new java.awt.Font("Caladea", 2, 14)); // NOI18N
        lblNumStat4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNumStat4.setText("NUM");

        lblNumStat5.setFont(new java.awt.Font("Caladea", 2, 14)); // NOI18N
        lblNumStat5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNumStat5.setText("NUM");

        lblNumStat6.setFont(new java.awt.Font("Caladea", 2, 14)); // NOI18N
        lblNumStat6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNumStat6.setText("NUM");

        btnIndietroStats.setFont(new java.awt.Font("Caladea", 2, 18)); // NOI18N
        btnIndietroStats.setText("X");
        btnIndietroStats.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255), new java.awt.Color(204, 153, 255), new java.awt.Color(255, 204, 255)));
        btnIndietroStats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIndietroStatsMouseClicked(evt);
            }
        });
        btnIndietroStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndietroStatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStatisticheTitolo)
                .addGap(89, 89, 89)
                .addComponent(btnIndietroStats, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblParchMaxPosti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblParchMinPosti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotAutoParch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMaxAutoParch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMediaAutoParch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMediaNViaggi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumStat1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumStat2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumStat3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumStat6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumStat5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumStat4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatisticheTitolo)
                    .addComponent(btnIndietroStats, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblParchMaxPosti)
                        .addGap(18, 18, 18)
                        .addComponent(lblParchMinPosti))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumStat1)
                        .addGap(18, 18, 18)
                        .addComponent(lblNumStat2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotAutoParch)
                    .addComponent(lblNumStat3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxAutoParch)
                    .addComponent(lblNumStat4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMediaAutoParch)
                    .addComponent(lblNumStat5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMediaNViaggi)
                    .addComponent(lblNumStat6))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIndietroStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndietroStatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIndietroStatsActionPerformed

    private void btnIndietroStatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIndietroStatsMouseClicked
        setVisible(false);
    }//GEN-LAST:event_btnIndietroStatsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistiche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIndietroStats;
    private javax.swing.JLabel lblMaxAutoParch;
    private javax.swing.JLabel lblMediaAutoParch;
    private javax.swing.JLabel lblMediaNViaggi;
    private javax.swing.JLabel lblNumStat1;
    private javax.swing.JLabel lblNumStat2;
    private javax.swing.JLabel lblNumStat3;
    private javax.swing.JLabel lblNumStat4;
    private javax.swing.JLabel lblNumStat5;
    private javax.swing.JLabel lblNumStat6;
    private javax.swing.JLabel lblParchMaxPosti;
    private javax.swing.JLabel lblParchMinPosti;
    private javax.swing.JLabel lblStatisticheTitolo;
    private javax.swing.JLabel lblTotAutoParch;
    // End of variables declaration//GEN-END:variables
}
